version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/guess_game
      SECRET_KEY: my_secret_key
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guess_game
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - backend

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
